[build]
  publish = "dist"
  command = "npm run build"

# SPA routing for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables for build (REMOVE SENSITIVE DATA)
[build.environment]
  NODE_VERSION = "18"
  # IMPORTANT: Remove sensitive environment variables from here
  # Set them in Netlify dashboard instead